
# function to perform and aggregate Wald stats on sample data
perform_and_aggregate <- function(.) {
  
  . <- as_tibble(.)
  
  tibble(
    tm_1_0 = compute_stats(rand_draw = ., tau = 0.01, m = 0),
    tm_1_2 = compute_stats(rand_draw = ., tau = 0.01, m = 2),
    tm_1_4 = compute_stats(rand_draw = ., tau = 0.01, m = 4),
    tm_1_6 = compute_stats(rand_draw = ., tau = 0.01, m = 6),
    tm_1_8 = compute_stats(rand_draw = ., tau = 0.01, m = 8),
    tm_1_10 = compute_stats(rand_draw = ., tau = 0.01, m = 10),
    tm_1_inf = compute_stats(rand_draw = ., tau = 0.01, m = NA),
    tm_2_0 = compute_stats(rand_draw = ., tau = 0.02, m = 0),
    tm_2_2 = compute_stats(rand_draw = ., tau = 0.02, m = 2),
    tm_2_4 = compute_stats(rand_draw = ., tau = 0.02, m = 4),
    tm_2_6 = compute_stats(rand_draw = ., tau = 0.02, m = 6),
    tm_2_8 = compute_stats(rand_draw = ., tau = 0.02, m = 8),
    tm_2_10 = compute_stats(rand_draw = ., tau = 0.02, m = 10),
    tm_2_inf = compute_stats(rand_draw = ., tau = 0.02, m = NA),
    tm_3_0 = compute_stats(rand_draw = ., tau = 0.03, m = 0),
    tm_3_2 = compute_stats(rand_draw = ., tau = 0.03, m = 2),
    tm_3_4 = compute_stats(rand_draw = ., tau = 0.03, m = 4),
    tm_3_6 = compute_stats(rand_draw = ., tau = 0.03, m = 6),
    tm_3_8 = compute_stats(rand_draw = ., tau = 0.03, m = 8),
    tm_3_10 = compute_stats(rand_draw = ., tau = 0.03, m = 10),
    tm_3_inf = compute_stats(rand_draw = ., tau = 0.03, m = NA),
    tm_4_0 = compute_stats(rand_draw = ., tau = 0.04, m = 0),
    tm_4_2 = compute_stats(rand_draw = ., tau = 0.04, m = 2),
    tm_4_4 = compute_stats(rand_draw = ., tau = 0.04, m = 4),
    tm_4_6 = compute_stats(rand_draw = ., tau = 0.04, m = 6),
    tm_4_8 = compute_stats(rand_draw = ., tau = 0.04, m = 8),
    tm_4_10 = compute_stats(rand_draw = ., tau = 0.04, m = 10),
    tm_4_inf = compute_stats(rand_draw = ., tau = 0.04, m = NA),
    tm_5_0 = compute_stats(rand_draw = ., tau = 0.05, m = 0),
    tm_5_2 = compute_stats(rand_draw = ., tau = 0.05, m = 2),
    tm_5_4 = compute_stats(rand_draw = ., tau = 0.05, m = 4),
    tm_5_6 = compute_stats(rand_draw = ., tau = 0.05, m = 6),
    tm_5_8 = compute_stats(rand_draw = ., tau = 0.05, m = 8),
    tm_5_10 = compute_stats(rand_draw = ., tau = 0.05, m = 10),
    tm_5_inf = compute_stats(rand_draw = ., tau = 0.05, m = NA),
    tm_6_0 = compute_stats(rand_draw = ., tau = 0.06, m = 0),
    tm_6_2 = compute_stats(rand_draw = ., tau = 0.06, m = 2),
    tm_6_4 = compute_stats(rand_draw = ., tau = 0.06, m = 4),
    tm_6_6 = compute_stats(rand_draw = ., tau = 0.06, m = 6),
    tm_6_8 = compute_stats(rand_draw = ., tau = 0.06, m = 8),
    tm_6_10 = compute_stats(rand_draw = ., tau = 0.06, m = 10),
    tm_6_inf = compute_stats(rand_draw = ., tau = 0.06, m = NA),
    tm_7_0 = compute_stats(rand_draw = ., tau = 0.07, m = 0),
    tm_7_2 = compute_stats(rand_draw = ., tau = 0.07, m = 2),
    tm_7_4 = compute_stats(rand_draw = ., tau = 0.07, m = 4),
    tm_7_6 = compute_stats(rand_draw = ., tau = 0.07, m = 6),
    tm_7_8 = compute_stats(rand_draw = ., tau = 0.07, m = 8),
    tm_7_10 = compute_stats(rand_draw = ., tau = 0.07, m = 10),
    tm_7_inf = compute_stats(rand_draw = ., tau = 0.07, m = NA),
    tm_8_0 = compute_stats(rand_draw = ., tau = 0.08, m = 0),
    tm_8_2 = compute_stats(rand_draw = ., tau = 0.08, m = 2),
    tm_8_4 = compute_stats(rand_draw = ., tau = 0.08, m = 4),
    tm_8_6 = compute_stats(rand_draw = ., tau = 0.08, m = 6),
    tm_8_8 = compute_stats(rand_draw = ., tau = 0.08, m = 8),
    tm_8_10 = compute_stats(rand_draw = ., tau = 0.08, m = 10),
    tm_8_inf = compute_stats(rand_draw = ., tau = 0.08, m = NA)
  )
  
}
